# Отчет по найденным ошибкам
## Найденные ошибки
В двух тестах найдены ошибки: test_get_age, test_is_homeless. Текст ошибки **NameError: name 'datetime' is not defined**.
## Исправления
В функции is_homeless не было прописано self перед вызовом свойства.   
В функции get_age был использован пакет datetime, но забыт импорт этой библиотеки